### ISSUE TITLE
m7lib incompatiblitity under OSMC Raspberry Pi

### ISSUE THREAD

**Issue by ExTechOp** [mhancoc7/kodi-addons#10]
**Describe the bug**
Unable to install m7lib on Rasberry Pi OSMC Kodi due to Python version incompatibility

**To Reproduce**
1. Run on your Raspberry Pi the current [OSMC](https://osmc.tv/) 2021.08-1 (Kodi 19.0.1 Matrix)
2. Add mhancoc7 repository
3. Attempt to install eg. "Free Live TV"
4. Error message popup "m7lib: the add-on is not compatible with this version of Kodi"
5. Further error message popup "The dependency on xmbc.python version 2.20.0 could not be satisfied"

**Expected behavior**
"Free Live TV" package gets installed.

**Additional information**
Checking out on the Raspberry Pi via ssh, it seems the selection of available Python versions is:
* python, python2, and python2.7 are version 2.7.16
* python3.5 and python3.5m are version 3.5.3
* python3, python3m, python3.7, and python3.7m are version 3.7.3

**Comment by jeremehancock** [comment]
I haven't been able to replicate this issue on Kodi 19 on other devices. I don't have an OSCM setup to test with. Do you have the latest version of Free Live TV?

**Comment by ExTechOp** [comment]
On this setup I "don't have" a version of Free Live TV, as this is an problem preventing getting it installed. Kodi/osmc is attempting to install version 0.7.0 from your repository, which I believe is the latest available?
