### ISSUE TITLE
Channel List and LiveTV Access

### ISSUE THREAD

**Issue by gregimagines** [mhancoc7/kodi-addons#12]
I am using FreeLiveTV 4k18 (planning to upgrade to Kodi 19 and 4k19 soon). Would love to see an option to select which channels we have listed and be able to get to the channels from the LiveTV menu item instead of going through the add-ons window to open this add-on. 

We have no need for all the foreign language channels, nor all the news channels. Would love to just select the channels we want to have listed and search through. Love having all the options but makes it harder to use and learn since we don't know what all is there to just search for. 

We currently have IPTV-Merge with a custom m3u (not great success with sources) and we can get to it from the home menu of Kodi in the LiveTV menu option that is populated. We are able to change the TV Group but I don't see this in there and the only way to get to it is running through Add-ons > Video Add-ons > Free Live TV....

**Comment by jeremehancock** [comment]
Hi, Thank you for your interest in the Free Live TV addon.

You mentioned  "FreeLiveTV 4k18". I did a quick google search for that and that appears to be a clone of my addon. So first I would highly recommend that you only use my addons from the official source. [https://m7kodi.dev/](https://m7kodi.dev/)

I can't be sure what this clone might have altered within my code. 

As for your question... I am not currently actively developing my Kodi Addons. However, I did take a look at IPTV Merge. Looks interesting. Unfortunately Free Live TV doesn't provide a playlist to use with it. I will keep this in mind if I have time in the future to make some improvements to Free Live TV. Thanks
