### ISSUE TITLE
Alphabetical Order Sort Setting

### ISSUE THREAD

**Issue by missjane63** [mhancoc7/kodi-addons#13]
Addon could use an Alphabetical Order Sort Setting.  

Menus and items inside menus are not sorted alphabetically (by title).  A setting to allow this would make finding content much easier when browsing and give the addon a more logical look

**Comment by jeremehancock** [comment]
Thank you for your interest in my addons. I am not currently actively developing any of my addons, but I will keep this in mind for future improvements if I get time to work on them. Thanks
