### ISSUE TITLE
some videos do not stream

### ISSUE THREAD

**Issue by vbtony** [mhancoc7/kodi-addons#14]
**Describe the bug**
most videos and tv channels stream flawlessly, it seems like new stuff won't stream also nothing is listed under live news folder

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug Log**
Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tubi.m7/?mode=600026play-tubitv]

**Additional context**

**Comment by jeremehancock** [comment]
@vbtony Sorry for the extreme delay in responding. This project has been somewhat dead for a while. I am going to officially retire my Kodi addons.
