### ISSUE TITLE
K20 compatibility

### ISSUE THREAD

**Issue by MacaroniSlick** [mhancoc7/kodi-addons#15]
**Is your feature request related to a problem? Please describe.**

ARE YOU GOING TO MAKE TUBI COMPATIBLE WITH K20?

PLEASE DO SO, N LET ME KNOW...

THANXEVERSOMUCH 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeremehancock** [comment]
@MacaroniSlick Unfortunately, I am going to be retiring my Kodi addons. I no longer use Kodi and I don't have time to maintain the project any longer.
