### ISSUE TITLE
Performance/responsiveness tweak animaltv/m7lib

### ISSUE THREAD

**Issue by Cheddoleum** [mhancoc7/kodi-addons#6]
Hi. I get a lot of enjoyment out of your animaltv wrapper for the explore.org livecams; thanks very much.  

However I did find myself wishing for a reduction of the delay in loading and refreshing the directory. On a Pi4 using NFSroot it takes 10-15 secs to load and reload the directory; both on returning to the directory after stopping a stream as well as on initial load.  A little of this is due to reading the explore.org web directory each time, but mostly it's the individual calls to xbmcplugin.addDirectoryItem for each item. Tried a couple of tweaks to the code:

1. Cache the explore.org web directory results for about 15 minutes, so it doesn't have to refresh from the web each time when prowling around.
2. Create an add_streams method to use xbmcplugin.addDirectoryItems for the entire stream list rather than individual calls per stream to addDirectoryItem.

No. 2 is the big win. A call that uses almost 0.1secs per item on a not particularly performant local database connection (i.e. NFSroot) now takes no more than a second for the entire list.   But I include No. 1 below anyway.

Here's a plain text diff; sorry for not doing this in a DCVS way but it's not against the repo proper, just working on the filesystem as deployed:

animaltv  lib/modules/common.py:

```@@ -18,6 +18,8 @@
 
 import os
 import sys
+import time
+import pickle
 import xbmc
 import xbmcgui
 import xbmcaddon
@@ -35,6 +37,7 @@
 addon_name = addon.getAddonInfo('name')
 addon_id = addon.getAddonInfo('id')
 plugin_path = xbmcaddon.Addon(id=addon_id).getAddonInfo('path')
+data_path = xbmc.translatePath(xbmcaddon.Addon(id=addon_id).getAddonInfo('profile'))
 patreon_logo = xbmc.translatePath(os.path.join(plugin_path, 'resources', 'images', 'patreon.jpg'))
 icon = xbmc.translatePath(os.path.join(plugin_path, 'icon.png'))
 fanart = xbmc.translatePath(os.path.join(plugin_path, 'icon.png'))
@@ -61,18 +64,22 @@
         set_setting('patreon_notify', "0")
 
 
-def stream_list():
-    try:
-        streams = m7lib.Stream.get_explore_org_streams()
-        for stream in sorted(streams, key=lambda k: k['title']):
-            if (sys.version_info > (3, 0)):
-                # Python 3
-                m7lib.Common.add_channel(stream["id"], stream["icon"], stream["fanart"], stream["title"].decode('UTF-8'))
-            else:
-                # Python 2
-                m7lib.Common.add_channel(stream["id"], stream["icon"], stream["fanart"], stream["title"])
-    except StandardError:
-        dlg_oops(addon_name)
+
+def stream_list():
+    try:
+        fname = data_path + "/streams.cache"
+        if os.path.exists(fname) and os.stat(fname).st_mtime > time.time() - 1200:
+            with open(fname,'rb') as f:
+                streams = pickle.load(f)
+        else:
+            streams = sorted(m7lib.Stream.get_explore_org_streams(), key=lambda k: k['title'])
+            with open(fname,'wb') as f:
+                pickle.dump(streams,f)
+
+        m7lib.Common.add_streams(streams)
+
+    except StandardError:
+        dlg_oops(addon_name)
 
 
 def play_stream(video_id):
```

m7lib lib/m7lib.py:

```@@ -116,6 +116,25 @@
         return channel_list
 
     @staticmethod
+    def add_streams(streams):
+        coll = []
+        for stream in streams:
+            # m7lib.Common.add_channel(stream["id"], stream["icon"], stream["fanart"], stream["title"])
+            icon = stream['icon']
+            fanart = stream['fanart']
+            u = sys.argv[0] + '?mode=' + str(stream['id']) + '&pvr=.pvr'
+            item = stream['title'] if stream['title'] is not None else stream['id']
+            liz = xbmcgui.ListItem(str(item), offscreen=True, iconImage=icon, thumbnailImage=icon)
+            liz.setProperty('skipPlayCount', 'true')
+            liz.setProperty('IsPlayable','true')
+            liz.setContentLookup(False)
+            liz.setIsFolder(False)
+            liz.setInfo('video', {'Title': item}) 
+            coll.append((u,liz,False))
+        return xbmcplugin.addDirectoryItems(int(sys.argv[1]), coll)
+
+
+    @staticmethod
     def add_channel(mode, icon, fanart, title=None, live=True):
         if live is True:
             u = sys.argv[0] + "?mode=" + str(mode) + "&pvr=.pvr"
```

Admittedly just a quick hack for my own use and not especially production grade but works very efficiently in practice: directory refreshes happen at basically UI speeds now without appreciable delay, greatly enhancing the fun and responsiveness of browsing the channels.  Thanks again.

**Comment by jeremehancock** [comment]
@Cheddoleum Thanks for your contribution! I have implemented the changes that you have provided. Definitely nice to speed things up. I am also glad that you are enjoying Animal TV.
