### ISSUE TITLE
Nice add-ons

### ISSUE THREAD

**Issue by mrgsi** [mhancoc7/kodi-addons#7]
Just discovered your repo today ad it works great in Kodi 19. Downloading is easy, but a shortcut URL would help those who prefer to type a link into their Kodi File Manager. 
Also as a Canadian, I'd be interested in a list of some Live Canadian channels. 
I can also promote your repo on reddit.com/r/Addons4Kodi if you are interested.

**Comment by mhancoc7** [comment]
Thank you for your suggestions. I am glad that you are enjoying them. I am still working to get them fully working on Kodi 19. I am still having issues with the addon icons not showing on some Android devices. If you have any legit online sources for Live Canadian channels I will definitely look at adding them. I am not actively trying to promote these addons as this is more of a side project. However, feel free to let others know if you would like. :)

**Comment by mrgsi** [comment]
I had a jen add-on for Kodi 18.9 that used Fluxus IPTV links which I separated into US and Canada. Not all of them worked but you get used to that with IPTV stuff. lol You can view the playlist links here: https://fluxustv.blogspot.com/p/m3u-list.html#gsc.tab=0

**Comment by jeremehancock** [comment]
Thanks for info on those channels. I have looked at Fluxus before. Currently I am only working to update channels that are easily pulled from sites directly and not pulled from services that I can't verify the streams.
