### ISSUE TITLE
Just a quick question...

### ISSUE THREAD

**Issue by mfreeman72** [mhancoc7/kodi-addons#8]
Hey there! I love your addons! I've been using them for quite a while now, and appreciate what you and other addon creators do!

I've noticed that you've started updating your the addons in your repository for Kodi 19 compatibility. Unfortunately, the distribution I use for our Raspberry Pi 3B+ based media center on our TV (OSMC) is not going to upgrade until 19.1 comes out, and from what I've read, I may or may not upgrade at that point, either, as there are some regressions in Raspberry Pi hardware acceleration with Kodi 19. Anyway, I've noticed updates are now failing on my system. Do you happen to keep both a Kodi 18.x and 19 repository, or just the one? I just want to make sure I'm using the right one, as I know some addon creators keep two different repos - one for the latest and one for the previous/legacy version. If you don't that's totally cool. But if you do, and I'm not on the right one, I'd love to know so I can continue to enjoy your addons and keep them as up-to-date as possible on my Kodi 18.9 system.

Thanks!

**Comment by jeremehancock** [comment]
Thank you for your interest in my addons. I have just pushed updates that I hope will ensure they work on both Kodi 19 and 18. I don't have things setup to properly test Kodi 18 so if you could update my addons and let me know if you are still having issues it would really help me out. If they are working just report any bugs with a new issue here.

Thanks so much!

**Comment by mfreeman72** [comment]
When I try to update your addons, it tells me there is a dependency problem: "The dependency on xbmc.python version 3.0.0 could not be satisfied."

**Comment by jeremehancock** [comment]
Which addons are giving that error? I have removed the dependency on python 3 so I believe the latest versions of my addons should at least install for you.

**Comment by mfreeman72** [comment]
Actually, I think the problem was on my end. I had all auto-updates turned off from before because it would constantly tell me the addons couldn't update. I think when I went to update them now, it hadn't read the changes to your repository yet. Now it has. Anyway, everything seems fine now. Thank you!

**Comment by jeremehancock** [comment]
Awesome! Please let me know if find any bugs.
